apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-4
  labels:
    app: sample-4
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-4
  template:
    metadata:
      labels:
        app: sample-4
    spec:
      containers:
        - name: sample-4
          image: devopsprosamples/next-sample-2
          ports:
            - containerPort: 3000
