apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-2
  labels:
    app: sample-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-2
  template:
    metadata:
      labels:
        app: sample-2
    spec:
      containers:
        - name: sample-2
          image: devopsprosamples/next-path-sample-2
          ports:
            - containerPort: 3000
