apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-1
  labels:
    app: sample-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-1
  template:
    metadata:
      labels:
        app: sample-1
    spec:
      containers:
        - name: sample-1
          image: devopsprosamples/next-path-sample-1
          ports:
            - containerPort: 80
